version = 1

test_patterns = ["**/test/**"]

exclude_patterns = ["examples/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  environment = [
    "browser",
    "jest",
    "mocha"
  ]
  dependency_file_paths = [
  '/packages/cdk8s-cli/',
  '/packages/cdk8s-plus-17/',
  '/packages/cdk8s/'
  ]
